version: "3.9"

networks:
  kafka-net:
    name: kafka-net
    driver: bridge

services:
  sftp:
    image: atmoz/sftp
    container_name: sftp-server
    restart: unless-stopped
    networks:
      - kafka-net
    ports:
      - "2222:22"
    command: sftpuser:sftppassword:::sink-output
    #command: sh -c "chmod -R 777 /home/sftpuser/sink-output && exec /entrypoint.sh sftpuser:sftppassword:::sink-output"
    volumes:
      - sftp-data:/home/sftpuser/sink-output

  postgres:
    image: postgres:16.3-alpine3.20
    container_name: postgres
    restart: unless-stopped
    networks:
      - kafka-net
    ports:
      - "5432:5432"
    volumes:
      - "./postgresql/postgresql.conf:/etc/postgresql/postgresql.conf"
      - "./postgresql/docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/"
      - postgres-data:/var/lib/postgresql/data
    #command: postgres -c config_file=/etc/postgresql/postgresql.conf
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.0
    container_name: elasticsearch
    restart: unless-stopped
    networks:
      - kafka-net
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=true 
      - xpack.security.authc.api_key.enabled=true
      - ELASTIC_PASSWORD=changeme 
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms4g -Xmx4g"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data

  # kibana:
  #   image: docker.elastic.co/kibana/kibana:8.13.0
  #   container_name: kibana
  #   restart: unless-stopped
  #   networks:
  #     - kafka-net
  #   ports:
  #     - "5601:5601"
  #   environment:
  #     - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
  #     - ELASTICSEARCH_USERNAME=elastic
  #     - ELASTICSEARCH_PASSWORD=changeme

volumes:
  elasticsearch-data:
  postgres-data:
  sftp-data:
