version: "3.9"

networks:
  kafka-net:
    name: kafka-net
    driver: bridge

services:
  conduktor-console:
    image: conduktor/conduktor-console:1.32.0
    container_name: conduktor-console
    depends_on:
      - postgresql
    networks:
      - kafka-net
    ports:
      - "9080:8080"
    volumes:
      - conduktor_data:/var/conduktor
    environment:
      CDK_DATABASE_URL: "postgresql://postgres:postgres@postgresql:5432/conduktor-console"
      CDK_CLUSTERS_0_ID: "local-kafka"
      CDK_CLUSTERS_0_NAME: "local-kafka"
      CDK_CLUSTERS_0_BOOTSTRAPSERVERS: "redpanda-kafka-alternative:9092"
      CDK_CLUSTERS_0_SCHEMAREGISTRY_URL: "http://redpanda-kafka-alternative:18081"
      CDK_CLUSTERS_0_COLOR: "#6A57C8"
      CDK_CLUSTERS_0_ICON: "kafka"
      CDK_CLUSTERS_1_ID: "cdk-gateway"
      CDK_CLUSTERS_1_NAME: "cdk-gateway"
      CDK_CLUSTERS_1_BOOTSTRAPSERVERS: "conduktor-gateway:6969"
      CDK_CLUSTERS_1_SCHEMAREGISTRY_URL: "http://redpanda-kafka-alternative:18081"
      CDK_CLUSTERS_1_KAFKAFLAVOR_URL: "http://conduktor-gateway:8888"
      CDK_CLUSTERS_1_KAFKAFLAVOR_USER: "admin"
      CDK_CLUSTERS_1_KAFKAFLAVOR_PASSWORD: "conduktor"
      CDK_CLUSTERS_1_KAFKAFLAVOR_VIRTUALCLUSTER: "passthrough"
      CDK_CLUSTERS_1_KAFKAFLAVOR_TYPE: "Gateway"
      CDK_CLUSTERS_1_COLOR: "#6A57C8"
      CDK_CLUSTERS_1_ICON: "dog"
      CDK_MONITORING_CORTEX-URL: "http://conduktor-monitoring:9009/"
      CDK_MONITORING_ALERT-MANAGER-URL: "http://conduktor-monitoring:9010/"
      CDK_MONITORING_CALLBACK-URL: "http://conduktor-console:8080/monitoring/api/"
      CDK_MONITORING_NOTIFICATIONS-CALLBACK-URL: "http://localhost:8080"

  postgresql:
    image: postgres:16.3-alpine3.20
    container_name: postgres-kafka-ui
    hostname: postgresql
    networks:
      - kafka-net
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      PGDATA: "/var/lib/postgresql/data"
      POSTGRES_DB: "conduktor-console"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_HOST_AUTH_METHOD: "scram-sha-256"

  conduktor-monitoring:
    image: conduktor/conduktor-console-cortex:1.27.0
    container_name: conduktor-monitoring
    networks:
      - kafka-net
    environment:
      CDK_CONSOLE-URL: "http://conduktor-console:8080"

volumes:
  pg_data: {}
  conduktor_data: {}
